# site settings
title: Newtown Independent Custom Computers
subtitle: 
email: custom@david-way.uk
description: Performance computers designed for your needs
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: David Way
street_address:
city: Newtown
state: Powys
zip_code:
country: United Kingdom
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub:
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
